name: 'Save dependabot changes'
description: "Check if dependencies were changed by dependabot and commit the new dependency information."
inputs:
  github_token:
    description: |
      Token used to commit changes back into the repository. 
      This should be a personal access token, or commits made by this action won't trigger a new workflow run.
      See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow for more info.
    required: true

outputs:
  is_dirty:
    description: "If there were changes made by dependabot, this variable will be true"
    value: ${{ steps.check-dirty.outputs.DIRTY == 'true' }}

runs:
  using: "composite"
  steps:
    - name: Check preconditions
      id: preconditions
      shell: bash
      run: |
        SOURCE_BRANCH="${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}"

        if [[ "${GITHUB_ACTOR}" != 'dependabot[bot]' ]]; then
          echo '::notice:: Action save-dependabot-changes is being skipped because actor is not dependabot'
          echo "SKIP=true" >> $GITHUB_OUTPUT
          exit
        fi        
        
        if [[ "${GITHUB_REF_TYPE}" != 'branch' ]]; then
          echo '::notice:: Action save-dependabot-changes is being skipped because workflow is not running against a branch'
          echo "SKIP=true" >> $GITHUB_OUTPUT
          exit
        fi        

    - name: Check if dependencies changed
      if: steps.preconditions.outputs.SKIP != 'true'
      shell: bash
      id: check-dirty
      run: $GITHUB_ACTION_PATH/is_dirty.sh

    - name: Update git credentials
      if: steps.check-dirty.outputs.DIRTY == 'true'
      shell: bash
      run: |
        set -o pipefail
        AUTH=$(printf "%s""pat:${{ inputs.github_token }}" | base64)
        echo "::add-mask::${AUTH}"
        git config --local http.https://github.com/.extraheader "AUTHORIZATION: basic ${AUTH}"

    - name: Commit updated dependency files
      if: steps.check-dirty.outputs.DIRTY == 'true'
      shell: bash
      run: $GITHUB_ACTION_PATH/commit.sh
