name: quality-assurance
on: [push]
jobs:
  check:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          #- windows-latest
        go_version:
          - '1.15.0'
          - '1.16.0'
          - '1.17.0'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~${{ matrix.go_version }}'
      - run: go test -race ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          # Specify the most recent (1.Y.Z) Y release
          go-version: '~1.17.0'
      - run: make lint
