name: quality-assurance
on: [push]
jobs:
  check:
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          #- windows-latest
        go_version:
          - '1.16.0'
          - '1.17.0'
          - '1.18.0'
          - '1.19.0'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '~${{ matrix.go_version }}'
          cache: true
      - run: |
          if [[ "${{runner.debug}}" == "1" ]]; then
            DEBUG_FLAGS="-v"
          fi
          
          go test -race ${DEBUG_FLAGS} ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          # Specify the most recent (1.Y.Z) Y release
          go-version-file: go.mod
          cache: true
      - run: make lint
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          # Since `types.go` varies based on the exact version of Go,
          # pin an exact (1.Y.Z) Z release.
          go-version-file: go.mod
          cache: true
      - run: make generate
      - run: |
          git add .
          if [[ -n "$(git status --porcelain)" ]]; then
             PAGER= git diff --cached
             exit 1
          fi
